datasets:
  - config/1kg_high_cov_hg38.yaml
  - config/1kg_low_cov_hg19.yaml
  - config/1kg_low_cov_hg38.yaml
  - config/gorilla_hg38.yaml
  - config/pan_hg38.yaml
  - config/pongo_hg38.yaml

selscan_config: "config/selscan.yaml"
betascan_config: "config/betascan.yaml"
dadi_config: "config/dadi-cli.yaml"
scikit_allel_config: "config/scikit-allel.yaml"

population_groups:
  AFR:
    color: "#E41A1C"
    populations: [YRI, LWK, GWD, MSL, ESN, ASW, ACB]
  EUR:
    color: "#377EB8"
    populations: [CEU, TSI, FIN, GBR, IBS]
  SAS:
    color: "#4DAF4A"
    populations: [GIH, PJL, BEB, STU, ITU]
  EAS:
    color: "#FF7F00"
    populations: [CHB, JPT, CHS, CDX, KHV]
  AMR:
    color: "#984EA3"
    populations: [MXL, PUR, CLM, PEL]
  Gorilla:
    color: "#A65628"
    populations: [GBB, GBG, GGG]
  Pan:
    color: "#F781BF"
    populations: [PPA, PTE, PTS, PTV, PTT]
  Pongo:
    color: "#999999"
    populations: [PP, PA]
